### ISSUE TITLE
Post-tink_lang era

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.storybook#5]
Now that coconut does not depends on tink_lang, I wonder what change should be made to this?

https://github.com/MVCoconut/coconut.storybook/blob/3ec86e833a350e98d8df950c336f5db0f997302e/src/coconut/storybook/Setup.hx#L13

@back2dos

**Comment by back2dos** [comment]
There's no problem using both libs together. I just didn't want to have it as a mandatory dependency in the core . I think you add it as a dependency here, it should work fine. Or do you feel pressed to get rid of it too? ^^

**Comment by kevinresol** [comment]
I just wonder if this "after tink.lang.Sugar" is still valid, because seems that the hxx transformation is no longer done by tink_lang.

**Comment by back2dos** [comment]
Hmm, as far as I can tell [that macro only affects stories, not views](https://github.com/MVCoconut/coconut.storybook/blob/3ec86e833a350e98d8df950c336f5db0f997302e/src/coconut/storybook/Setup.hx#L18), so if you add tink_lang here, it should work as before, no?

**Comment by kevinresol** [comment]
Ah yes. Because tink_lang still supports hxx transformation.
